import { ToDo } from "./ToDo";

export const TODOS: ToDo [] = 
[{
    id: 1,
    title: "Todo 1",
    content: "Content todo 1",
    author: "John Doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 2,
    title: "ToDo 2",
    content: "Content todo 2",
    author: "John Doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 3,
    title: "ToDo 3",
    content: "Content todo 3",
    author: "John Doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 4,
    title: "ToDo 4",
    content: "Content todo 4",
    author: "John Doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 5,
    title: "ToDo 5",
    content: "Content todo 5",
    author: "John Doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 6,
    title: "ToDo 6",
    content: "Content todo 6",
    author: "John Doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 7,
    title: "ToDo 7",
    content: "Content todo 7",
    author: "John Doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 8,
    title: "ToDo 8",
    content: "Content todo 8",
    author: "John Doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 9,
    title: "ToDo 9",
    content: "Content todo 9",
    author: "John Doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
},
{
    id: 10,
    title: "ToDo 10",
    content: "Content todo 10",
    author: "John Doe",
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
}]